name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
      - test
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Minify HTML
        uses: tdewolff/minify-action@v2
        with:
          file: 'index.html'
          output: 'public/index.html'
          type: 'html'
      
      - name: Minify CSS
        uses: tdewolff/minify-action@v2
        with:
          file: 'styles.css'
          output: 'public/styles.css'
          type: 'css'
      
      - name: Minify JavaScript
        uses: tdewolff/minify-action@v2
        with:
          file: 'app.js'
          output: 'public/app.js'
          type: 'js'

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PURPLE_MOSS_08BFAF81E }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/public"
          api_location: ""
          output_location: ""
          production_branch: "main"

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PURPLE_MOSS_08BFAF81E }}
          action: "close"